### ISSUE TITLE
说明文档补充

### ISSUE THREAD

**Issue by karatttt** [ZhengqiZhuang/ZhengqiZhuang.github.io#1]
说明文档可以补充一个这个
```yaml
deploy:
  type: git
  repository: git@github.com:Fomalhaut-Blog/Fomalhaut-Blog.github.io.git
  branch: main
```
